; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28316.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\10737\AppData\Local\Temp\.NETFramework,Version=4.7.2.AssemblyAttributes.cpp"
